name: Build APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Unzip
        run: unzip -o inshae-ttbyq.zip
        
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Build & Gradle
        run: |
          if [ -f "package.json" ]; then npm install --legacy-peer-deps && npm run build --if-present && npx cap sync android; fi
          cd $(find . -name "gradlew" -exec dirname {} \; | head -n 1)
          chmod +x gradlew
          ./gradlew assembleDebug
          
      - uses: actions/upload-artifact@v4
        with:
          name: mawaeedi-app
          path: '**/build/outputs/apk/debug/*.apk'

